spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ici_think
    username: postgres
    password: xctj9950
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  datasource.embedded-database-connection: none

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.boot.autoconfigure.jdbc: debug
    org.springframework.boot.autoconfigure.orm.jpa: debug
